### ISSUE TITLE
REPL doesn't work

### ISSUE THREAD

**Issue by steeley** [Elizaveta239/intellij-micropython#196]
open the terminal for a RP pico board and you just get this:
```
Device path /dev/cu.usbmodem14101
Quit: Ctrl+] | Stop program: Ctrl+C | Reset: Ctrl+D
Type 'help()' (without the quotes) then press ENTER.
```

but you cannot type anything. PyCharm 2022.1.3 on OSX Big Sur

**Comment by vekunz** [comment]
For me, everything works fine. Maybe it is a problem with your Pico.

**Comment by andypiper** [comment]
What version of MicroPython do you have on the Pico?

**Comment by steeley** [comment]
was 1.18 - might try refreshing with 1.19
